#!/usr/bin/env python3
"""Render apply previews and prepare Jira payloads without writing to Jira.

For a valid command, main() returns 0 on success or 1 on validation, I/O, or
JSON errors; argparse usage errors exit 2. Previews always print to stdout;
actions print the payload there unless --output is set.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

from _common import (
    COMMITTABLE_SIZES,
    IMPACT_LABELS,
    NO_WORK,
    SIZES,
    TEAMS,
    markdown_cell,
    read_json,
    require_object,
    validate_context_name,
    write_files_transactionally,
    write_json,
)
from finalize_assessment import finalize_assessment, render_assessment


def _directory(context: str) -> Path:
    validate_context_name(context)
    return Path(".artifacts") / "sizing" / context


def _wiki_cell(value: Any) -> str:
    text = str(value or "").replace("\r", " ").replace("\n", " ").strip()
    return text.replace("|", "\\|")


def _drivers(feature: dict[str, Any]) -> list[str]:
    dimensions = feature["dimensions"]
    ranked = sorted(
        dimensions.items(),
        key=lambda item: ({"Very High": 0, "High": 1, "Medium": 2, "Low": 3}[item[1]["level"]], item[0]),
    )
    result = [
        f"{name.replace('_', ' ')}: {item['rationale']}"
        for name, item in ranked
        if item["level"] in {"High", "Very High"}
    ][:3]
    if not result:
        result = [item["rationale"] for _, item in ranked[:3]]
    return result


def jira_comment(feature: dict[str, Any]) -> str:
    size = feature["recommended_size"]
    lines = [
        "h2. Sizing Assessment",
        "",
        f"*Overall Size: {size}*",
        "",
        "||Team||Effort||Rationale||",
    ]
    for team in TEAMS:
        item = feature["teams"][team]
        rationale = item["rationale"] or NO_WORK.get(team, "")
        lines.append(f"|{team}|{item['size']}|{_wiki_cell(rationale)}|")
    lines.extend(["", "*Impact vs. Effort:*", "", "||Sub-dimension||Score||Rationale||"])
    for dimension, label in IMPACT_LABELS.items():
        item = feature["impact"][dimension]
        lines.append(f"|{label}|{item['score']}|{_wiki_cell(item['rationale'])}|")
    effort = feature["effort_score"] if feature["effort_score"] is not None else "Not scored"
    priority = f"{feature['priority_score']:.1f}" if feature["priority_score"] is not None else "Not scored"
    lines.extend([
        "",
        f"*Impact:* {feature['impact_score']}/20 ({feature['impact_band']}) | "
        f"*Effort:* {effort} ({size})",
        f"*Priority:* {priority} | *Quadrant:* {feature['quadrant']}",
        "",
        "*Key sizing drivers:*",
    ])
    lines.extend(f"- {_wiki_cell(driver)}" for driver in _drivers(feature))
    lines.extend(["", "_Generated by AI sizing workflow_"])
    return "\n".join(lines)


def render_preview(assessment: dict[str, Any]) -> str:
    features = assessment["features"]
    lines = [
        "## Apply Preview",
        "",
        "| # | Feature | Size to Set | Team Breakdown |",
        "|---|---------|-------------|----------------|",
    ]
    number = 0
    for feature in features:
        if feature["recommended_size"] == "XXL":
            continue
        number += 1
        teams = ", ".join(f"{team} {feature['teams'][team]['size']}" for team in TEAMS)
        lines.append(
            f"| {number} | {markdown_cell(feature['key'])}: {markdown_cell(feature['title'])} | "
            f"{feature['recommended_size']} | {markdown_cell(teams)} |"
        )
    if number == 0:
        lines.append("| — | No committable Features | — | — |")

    xxl = [item for item in features if item["recommended_size"] == "XXL"]
    if xxl:
        lines.extend([
            "",
            "## Excluded — XXL (Must Split)",
            "",
            "| Feature | Recommended Action |",
            "|---------|-------------------|",
        ])
        for feature in xxl:
            lines.append(
                f"| {markdown_cell(feature['key'])}: {markdown_cell(feature['title'])} | "
                "Split before committing — see split recommendations in the assessment |"
            )
    lines.extend([
        "",
        "No Jira changes have been made. This selection preview does not authorize Jira writes; review the prepared action payload before approving.",
    ])
    return "\n".join(lines) + "\n"


def _parse_overrides(
    values: list[str],
    known_keys: set[str],
    *,
    allow_xxl: bool = False,
) -> dict[str, str]:
    result: dict[str, str] = {}
    for value in values:
        if "=" not in value:
            raise ValueError(f"invalid override {value!r}; expected ISSUE-KEY=SIZE")
        key, raw_size = value.split("=", 1)
        key = key.strip()
        size = raw_size.strip().upper()
        if key not in known_keys:
            raise ValueError(f"override references unknown Feature {key}")
        allowed_sizes = SIZES if allow_xxl else COMMITTABLE_SIZES
        if size not in allowed_sizes:
            if allow_xxl:
                raise ValueError(f"restored override must be one of {', '.join(SIZES)}")
            raise ValueError(f"apply overrides must be one of {', '.join(COMMITTABLE_SIZES)}; rerun /assess to set XXL")
        result[key] = size
    return result


def _actions(assessment: dict[str, Any], selected_keys: set[str] | None) -> list[dict[str, Any]]:
    features = assessment["features"]
    all_keys = {item["key"] for item in features}
    if selected_keys is not None:
        unknown = selected_keys - all_keys
        if unknown:
            raise ValueError(f"selected Features contain unknown key(s): {', '.join(sorted(unknown))}")
    actions: list[dict[str, Any]] = []
    for feature in features:
        key = feature["key"]
        if selected_keys is not None and key not in selected_keys:
            continue
        size = feature["recommended_size"]
        if size == "XXL":
            continue
        actions.append({
            "key": key,
            "title": feature["title"],
            "size": size,
            "comment": jira_comment(feature),
        })
    return actions


def _updated_overrides(
    directory: Path,
    known_keys: set[str],
    overrides: dict[str, str],
    cleared_keys: set[str] | None,
) -> tuple[dict[str, Any], dict[str, Any], int]:
    decisions_path = directory / "02-decisions.json"
    context_path = directory / "01-context.json"
    decisions_obj = require_object(read_json(decisions_path), "decisions")
    context = read_json(context_path)
    previous = decisions_obj.get("user_overrides", {})
    if not isinstance(previous, dict):
        raise ValueError("decisions.user_overrides must be an object")
    keys_to_clear = set(previous) if cleared_keys is None else cleared_keys
    unknown = keys_to_clear - known_keys
    if unknown:
        raise ValueError(f"clear references unknown Feature key(s): {', '.join(sorted(unknown))}")
    overlap = set(overrides) & keys_to_clear
    if overlap:
        raise ValueError(f"cannot override and clear the same Feature key(s): {', '.join(sorted(overlap))}")
    removed = len(set(previous) & keys_to_clear)
    retained = {key: value for key, value in previous.items() if key not in keys_to_clear}
    decisions_obj["user_overrides"] = {**retained, **overrides}
    assessment = finalize_assessment(context, decisions_obj)
    return decisions_obj, assessment, removed


def _json_bytes(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def _validated_action_output_path(directory: Path, output_path: Path) -> Path:
    output_path = Path(os.path.abspath(output_path))
    if output_path.is_dir():
        raise ValueError("action payload output must be a file path")
    protected_names = (
        "01-context.json",
        "01-context.md",
        "02-decisions.json",
        "02-assessment.json",
        "02-assessment.md",
    )
    output_identity = Path(os.path.realpath(output_path))
    protected_paths = {
        Path(os.path.realpath(os.path.abspath(directory / name)))
        for name in protected_names
    }
    if output_identity in protected_paths:
        raise ValueError("action payload output cannot overwrite sizing context or assessment artifacts")
    return output_path


def _commit_override_update(
    directory: Path,
    decisions_obj: dict[str, Any],
    assessment: dict[str, Any],
    output_path: Path | None = None,
    payload: dict[str, Any] | None = None,
) -> None:
    decisions_path = Path(os.path.abspath(directory / "02-decisions.json"))
    assessment_path = Path(os.path.abspath(directory / "02-assessment.json"))
    markdown_path = Path(os.path.abspath(directory / "02-assessment.md"))
    action_path = Path(os.path.abspath(directory / "03-apply-actions.json"))
    files: dict[Path, bytes | None] = {
        decisions_path: _json_bytes(decisions_obj),
        assessment_path: _json_bytes(assessment),
        markdown_path: render_assessment(assessment).encode("utf-8"),
        action_path: None,
    }
    if output_path is not None:
        output_path = _validated_action_output_path(directory, output_path)
        if payload is None:
            raise ValueError("action payload is required when an output path is provided")
        files[output_path] = _json_bytes(payload)
        if output_path == action_path:
            files[action_path] = _json_bytes(payload)

    write_files_transactionally(files)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Prepare deterministic sizing apply previews and payloads.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    preview_parser = subparsers.add_parser("preview", help="Render the dry-run preview.")
    preview_parser.add_argument("context", help="Sizing artifact context directory name")
    action_parser = subparsers.add_parser("actions", help="Prepare selected Jira payloads for review.")
    action_parser.add_argument("context", help="Sizing artifact context directory name")
    action_parser.add_argument(
        "--all",
        action="store_true",
        help="Select all committable Features for the prepared action payload.",
    )
    action_parser.add_argument(
        "--select-key",
        action="append",
        dest="selected_keys",
        default=[],
        help="Feature key selected for the action payload; repeat as needed.",
    )
    action_parser.add_argument(
        "--approved-key",
        action="append",
        dest="selected_keys",
        default=argparse.SUPPRESS,
        help=argparse.SUPPRESS,
    )
    action_parser.add_argument(
        "--override",
        action="append",
        default=[],
        help="Selected size override in ISSUE-KEY=SIZE form; repeat as needed.",
    )
    action_parser.add_argument(
        "--clear-override",
        action="append",
        default=[],
        help="Remove a stored size override for ISSUE-KEY; repeat as needed.",
    )
    action_parser.add_argument(
        "--output",
        type=Path,
        help="Write payload JSON to this path instead of stdout.",
    )
    clear_parser = subparsers.add_parser(
        "clear-overrides",
        help="Restore original recommendations by removing stored apply-time overrides.",
    )
    clear_parser.add_argument("context", help="Sizing artifact context directory name")
    clear_parser.add_argument(
        "--key",
        action="append",
        dest="keys",
        default=[],
        help="Feature key to clear; repeat for multiple keys. Omit to clear every stored override.",
    )
    show_parser = subparsers.add_parser(
        "show-overrides",
        help="Print the compact map of stored apply-time overrides.",
    )
    show_parser.add_argument("context", help="Sizing artifact context directory name")
    restore_parser = subparsers.add_parser(
        "restore-overrides",
        help="Restore selected apply-time overrides after a canceled attempt.",
    )
    restore_parser.add_argument("context", help="Sizing artifact context directory name")
    restore_parser.add_argument(
        "--key",
        action="append",
        dest="keys",
        default=[],
        help="Feature key to remove from user_overrides; repeat as needed.",
    )
    restore_parser.add_argument(
        "--override",
        action="append",
        default=[],
        help="Prior size override to restore in ISSUE-KEY=SIZE form; repeat as needed.",
    )
    return parser


def _load_assessment(context: str) -> tuple[Path, dict[str, Any]]:
    directory = _directory(context)
    assessment_path = directory / "02-assessment.json"
    assessment = read_json(assessment_path)
    if not isinstance(assessment, dict) or not isinstance(assessment.get("features"), list):
        raise ValueError(f"{assessment_path} is not a finalized sizing assessment")
    return directory, assessment


def _known_keys(assessment: dict[str, Any]) -> set[str]:
    return {
        item["key"] for item in assessment["features"] if isinstance(item, dict)
    }


def _handle_preview(args: argparse.Namespace) -> None:
    _, assessment = _load_assessment(args.context)
    print(render_preview(assessment), end="")


def _handle_clear_overrides(args: argparse.Namespace) -> None:
    directory, assessment = _load_assessment(args.context)
    decisions_obj, updated_assessment, removed = _updated_overrides(
        directory,
        _known_keys(assessment),
        {},
        {key.strip() for key in args.keys} if args.keys else None,
    )
    _commit_override_update(directory, decisions_obj, updated_assessment)
    print(
        f"Cleared {removed} apply-time override(s); assessment restored for "
        f"{len(updated_assessment['features'])} Feature(s)."
    )


def _handle_show_overrides(args: argparse.Namespace) -> None:
    directory = _directory(args.context)
    decisions = require_object(read_json(directory / "02-decisions.json"), "decisions")
    overrides = require_object(decisions.get("user_overrides", {}), "decisions.user_overrides")
    print(json.dumps(overrides, ensure_ascii=False, separators=(",", ":")))


def _handle_restore_overrides(args: argparse.Namespace) -> None:
    directory, assessment = _load_assessment(args.context)
    known_keys = _known_keys(assessment)
    overrides = _parse_overrides(args.override, known_keys, allow_xxl=True)
    cleared_keys = {key.strip() for key in args.keys}
    decisions_obj, updated_assessment, _ = _updated_overrides(
        directory, known_keys, overrides, cleared_keys
    )
    _commit_override_update(directory, decisions_obj, updated_assessment)
    print(
        "Restored apply-time overrides; assessment rebuilt for "
        f"{len(updated_assessment['features'])} Feature(s)."
    )


def _selected_action_keys(
    args: argparse.Namespace,
    assessment: dict[str, Any],
    known_keys: set[str],
    overrides: dict[str, str],
) -> set[str] | None:
    if args.all and args.selected_keys:
        raise ValueError("use --all or --select-key, not both")
    if not args.all and not args.selected_keys:
        raise ValueError("select Features with --all or at least one --select-key")
    selected = None if args.all else set(args.selected_keys)
    xxl_keys = {
        item["key"] for item in assessment["features"]
        if item["recommended_size"] == "XXL"
    }
    if selected is not None:
        unknown = selected - known_keys
        if unknown:
            raise ValueError(f"selected Features contain unknown key(s): {', '.join(sorted(unknown))}")
        if selected & xxl_keys:
            raise ValueError("XXL Features cannot be selected for Jira updates")
    if set(overrides) & xxl_keys:
        raise ValueError("XXL Features cannot be overridden during apply; split the Feature and rerun /assess")
    if selected is not None and set(overrides) - selected:
        raise ValueError("every size override must belong to a selected Feature")
    return selected


def _updated_action_assessment(
    directory: Path,
    assessment: dict[str, Any],
    known_keys: set[str],
    overrides: dict[str, str],
    cleared_keys: set[str],
    selected: set[str] | None,
) -> tuple[dict[str, Any] | None, dict[str, Any], bool]:
    if not overrides and not cleared_keys:
        return None, assessment, False

    decisions_obj, updated_assessment, _ = _updated_overrides(
        directory, known_keys, overrides, cleared_keys
    )
    if selected is not None:
        restored_xxl = selected & {
            item["key"] for item in updated_assessment["features"]
            if item["recommended_size"] == "XXL"
        }
        if restored_xxl:
            raise ValueError(
                "clearing overrides makes selected Feature(s) XXL: "
                f"{', '.join(sorted(restored_xxl))}; deselect them or split and rerun /assess"
            )
    return decisions_obj, updated_assessment, True


def _action_payload(context: str, actions: list[dict[str, Any]]) -> dict[str, Any]:
    """Build ``03-apply-actions.json`` with context and key/title/size/comment actions.

    Each action's size is committable (XS through XL); ``comment`` contains the
    complete Jira wiki markup prepared for human review and approval.
    """
    return {"context": context, "actions": actions}


def _handle_actions(args: argparse.Namespace) -> None:
    directory, assessment = _load_assessment(args.context)
    known_keys = _known_keys(assessment)
    output_path = (
        _validated_action_output_path(directory, args.output)
        if args.output is not None
        else None
    )
    overrides = _parse_overrides(args.override, known_keys)
    cleared_keys = {value.strip() for value in args.clear_override}
    selected = _selected_action_keys(args, assessment, known_keys, overrides)
    decisions_obj, assessment, update_overrides = _updated_action_assessment(
        directory,
        assessment,
        known_keys,
        overrides,
        cleared_keys,
        selected,
    )
    payload = _action_payload(args.context, _actions(assessment, selected))

    if update_overrides:
        if decisions_obj is None:
            raise ValueError("updated decisions are missing")
        _commit_override_update(directory, decisions_obj, assessment, output_path, payload)
    if output_path is not None:
        if not update_overrides:
            write_json(output_path, payload)
        print(f"Prepared {len(payload['actions'])} Jira action(s) at {args.output}", file=sys.stderr)
    else:
        print(json.dumps(payload, ensure_ascii=False, separators=(",", ":")))


def _handle_command(args: argparse.Namespace) -> None:
    handlers = {
        "preview": _handle_preview,
        "actions": _handle_actions,
        "clear-overrides": _handle_clear_overrides,
        "show-overrides": _handle_show_overrides,
        "restore-overrides": _handle_restore_overrides,
    }
    handlers[args.command](args)


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    try:
        _handle_command(args)
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
