#!/usr/bin/env python3
"""Render an apply preview and prepare selected Jira update payloads."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

from _common import COMMITTABLE_SIZES, TEAMS, markdown_cell, read_json, require_object, write_json
from finalize_assessment import finalize_assessment, render_assessment


NO_WORK = {
    "UX": "No UX work identified",
    "UI": "No UI work identified",
    "DOCS": "No downstream docs work identified",
}


def _directory(context: str) -> Path:
    if context in {".", ".."} or "/" in context or "\\" in context:
        raise ValueError("context must be a single directory name")
    return Path(".artifacts") / "sizing" / context


def _wiki_cell(value: Any) -> str:
    text = str(value or "").replace("\r", " ").replace("\n", " ").strip()
    return text.replace("|", "\\|")


def _drivers(feature: dict[str, Any]) -> list[str]:
    dimensions = feature["dimensions"]
    ranked = sorted(
        dimensions.items(),
        key=lambda item: ({"Very High": 0, "High": 1, "Medium": 2, "Low": 3}[item[1]["level"]], item[0]),
    )
    result = [
        f"{name.replace('_', ' ')}: {item['rationale']}"
        for name, item in ranked
        if item["level"] in {"High", "Very High"}
    ][:3]
    if not result:
        result = [item["rationale"] for _, item in ranked[:3]]
    return result


def jira_comment(feature: dict[str, Any]) -> str:
    size = feature["recommended_size"]
    lines = [
        "h2. Sizing Assessment",
        "",
        f"*Overall Size: {size}*",
        "",
        "||Team||Effort||Rationale||",
    ]
    for team in TEAMS:
        item = feature["teams"][team]
        rationale = item["rationale"] or NO_WORK.get(team, "")
        lines.append(f"|{team}|{item['size']}|{_wiki_cell(rationale)}|")
    lines.extend(["", "*Impact vs. Effort:*", "", "||Sub-dimension||Score||Rationale||"])
    labels = {
        "user_reach": "User Reach",
        "pain_severity": "Pain Severity",
        "strategic_alignment": "Strategic Alignment",
        "dependency": "Dependency",
    }
    for dimension, label in labels.items():
        item = feature["impact"][dimension]
        lines.append(f"|{label}|{item['score']}|{_wiki_cell(item['rationale'])}|")
    effort = feature["effort_score"] if feature["effort_score"] is not None else "Not scored"
    priority = f"{feature['priority_score']:.1f}" if feature["priority_score"] is not None else "Not scored"
    lines.extend([
        "",
        f"*Impact:* {feature['impact_score']}/20 ({feature['impact_band']}) | "
        f"*Effort:* {effort} ({size})",
        f"*Priority:* {priority} | *Quadrant:* {feature['quadrant']}",
        "",
        "*Key sizing drivers:*",
    ])
    lines.extend(f"- {_wiki_cell(driver)}" for driver in _drivers(feature))
    lines.extend(["", "_Generated by AI sizing workflow_"])
    return "\n".join(lines)


def render_preview(assessment: dict[str, Any]) -> str:
    features = assessment["features"]
    lines = [
        "## Apply Preview",
        "",
        "| # | Feature | Size to Set | Team Breakdown |",
        "|---|---------|-------------|----------------|",
    ]
    number = 0
    for feature in features:
        if feature["recommended_size"] == "XXL":
            continue
        number += 1
        teams = ", ".join(f"{team} {feature['teams'][team]['size']}" for team in TEAMS)
        lines.append(
            f"| {number} | {markdown_cell(feature['key'])}: {markdown_cell(feature['title'])} | "
            f"{feature['recommended_size']} | {markdown_cell(teams)} |"
        )
    if number == 0:
        lines.append("| — | No committable Features | — | — |")

    xxl = [item for item in features if item["recommended_size"] == "XXL"]
    if xxl:
        lines.extend([
            "",
            "## Excluded — XXL (Must Split)",
            "",
            "| Feature | Recommended Action |",
            "|---------|-------------------|",
        ])
        for feature in xxl:
            lines.append(
                f"| {markdown_cell(feature['key'])}: {markdown_cell(feature['title'])} | "
                "Split before committing — see split recommendations in the assessment |"
            )
    lines.extend([
        "",
        "No Jira changes have been made. This selection preview does not authorize Jira writes; review the prepared action payload before approving.",
    ])
    return "\n".join(lines) + "\n"


def _parse_overrides(values: list[str], known_keys: set[str]) -> dict[str, str]:
    result: dict[str, str] = {}
    for value in values:
        if "=" not in value:
            raise ValueError(f"invalid override {value!r}; expected ISSUE-KEY=SIZE")
        key, raw_size = value.split("=", 1)
        key = key.strip()
        size = raw_size.strip().upper()
        if key not in known_keys:
            raise ValueError(f"override references unknown Feature {key}")
        if size not in COMMITTABLE_SIZES:
            raise ValueError(f"apply overrides must be one of {', '.join(COMMITTABLE_SIZES)}; rerun /assess to set XXL")
        result[key] = size
    return result


def _actions(assessment: dict[str, Any], selected_keys: set[str] | None) -> list[dict[str, Any]]:
    features = assessment["features"]
    all_keys = {item["key"] for item in features}
    if selected_keys is not None:
        unknown = selected_keys - all_keys
        if unknown:
            raise ValueError(f"selected Features contain unknown key(s): {', '.join(sorted(unknown))}")
    actions: list[dict[str, Any]] = []
    for feature in features:
        key = feature["key"]
        if selected_keys is not None and key not in selected_keys:
            continue
        size = feature["recommended_size"]
        if size == "XXL":
            continue
        actions.append({
            "key": key,
            "title": feature["title"],
            "size": size,
            "comment": jira_comment(feature),
        })
    return actions


def _updated_overrides(
    directory: Path,
    known_keys: set[str],
    overrides: dict[str, str],
    cleared_keys: set[str] | None,
) -> tuple[dict[str, Any], dict[str, Any], int]:
    decisions_path = directory / "02-decisions.json"
    context_path = directory / "01-context.json"
    decisions_obj = require_object(read_json(decisions_path), "decisions")
    context = read_json(context_path)
    previous = decisions_obj.get("user_overrides", {})
    if not isinstance(previous, dict):
        raise ValueError("decisions.user_overrides must be an object")
    keys_to_clear = set(previous) if cleared_keys is None else cleared_keys
    unknown = keys_to_clear - known_keys
    if unknown:
        raise ValueError(f"clear references unknown Feature key(s): {', '.join(sorted(unknown))}")
    overlap = set(overrides) & keys_to_clear
    if overlap:
        raise ValueError(f"cannot override and clear the same Feature key(s): {', '.join(sorted(overlap))}")
    removed = len(set(previous) & keys_to_clear)
    retained = {key: value for key, value in previous.items() if key not in keys_to_clear}
    decisions_obj["user_overrides"] = {**retained, **overrides}
    assessment = finalize_assessment(context, decisions_obj)
    return decisions_obj, assessment, removed


def _json_bytes(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def _write_files_transactionally(files: dict[Path, bytes | None]) -> None:
    """Replace related artifacts together and restore backups if a write fails."""
    staged: dict[Path, Path] = {}
    backup_dirs: list[Path] = []
    backups: list[tuple[Path, Path]] = []
    installed: list[Path] = []
    try:
        for target, contents in files.items():
            target.parent.mkdir(parents=True, exist_ok=True)
            if target.is_dir() and not target.is_symlink():
                raise IsADirectoryError(target)
            if contents is None:
                continue
            descriptor, temporary_name = tempfile.mkstemp(
                prefix=f".{target.name}.tmp-", dir=target.parent
            )
            temporary = Path(temporary_name)
            staged[target] = temporary
            with os.fdopen(descriptor, "wb") as stream:
                stream.write(contents)
                stream.flush()
                os.fsync(stream.fileno())

        for target in files:
            if not target.exists() and not target.is_symlink():
                continue
            backup_dir = Path(tempfile.mkdtemp(prefix=".apply-backup-", dir=target.parent))
            backup_dirs.append(backup_dir)
            backup = backup_dir / target.name
            backups.append((backup, target))
            os.replace(target, backup)

        for target, temporary in staged.items():
            installed.append(target)
            os.replace(temporary, target)
    except Exception as exc:
        rollback_errors: list[OSError] = []
        for target in reversed(installed):
            try:
                target.unlink(missing_ok=True)
            except OSError as rollback_error:
                rollback_errors.append(rollback_error)
        for backup, target in reversed(backups):
            if backup.exists() or backup.is_symlink():
                try:
                    os.replace(backup, target)
                except OSError as rollback_error:
                    rollback_errors.append(rollback_error)
        if rollback_errors:
            recovery_dirs = ", ".join(str(path) for path in backup_dirs)
            raise OSError(
                f"artifact update failed ({exc}); rollback was incomplete, "
                f"preserve recovery files in {recovery_dirs}"
            ) from exc
        for backup_dir in backup_dirs:
            shutil.rmtree(backup_dir, ignore_errors=True)
        raise
    else:
        for backup_dir in backup_dirs:
            shutil.rmtree(backup_dir, ignore_errors=True)
    finally:
        for temporary in staged.values():
            try:
                temporary.unlink(missing_ok=True)
            except OSError:
                pass


def _commit_override_update(
    directory: Path,
    decisions_obj: dict[str, Any],
    assessment: dict[str, Any],
    output_path: Path | None = None,
    payload: dict[str, Any] | None = None,
) -> None:
    decisions_path = Path(os.path.abspath(directory / "02-decisions.json"))
    assessment_path = Path(os.path.abspath(directory / "02-assessment.json"))
    markdown_path = Path(os.path.abspath(directory / "02-assessment.md"))
    action_path = Path(os.path.abspath(directory / "03-apply-actions.json"))
    state_paths = {decisions_path, assessment_path, markdown_path}
    files: dict[Path, bytes | None] = {
        decisions_path: _json_bytes(decisions_obj),
        assessment_path: _json_bytes(assessment),
        markdown_path: render_assessment(assessment).encode("utf-8"),
        action_path: None,
    }
    if output_path is not None:
        output_path = Path(os.path.abspath(output_path))
        if output_path in state_paths:
            raise ValueError("action payload output cannot overwrite sizing assessment artifacts")
        if payload is None:
            raise ValueError("action payload is required when an output path is provided")
        files[output_path] = _json_bytes(payload)
        if output_path == action_path:
            files[action_path] = _json_bytes(payload)

    _write_files_transactionally(files)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Prepare deterministic sizing apply previews and payloads.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    preview_parser = subparsers.add_parser("preview", help="Render the dry-run preview.")
    preview_parser.add_argument("context", help="Sizing artifact context directory name")
    action_parser = subparsers.add_parser("actions", help="Prepare selected Jira payloads for review.")
    action_parser.add_argument("context", help="Sizing artifact context directory name")
    action_parser.add_argument(
        "--all",
        action="store_true",
        help="Select all committable Features for the prepared action payload.",
    )
    action_parser.add_argument(
        "--approved-key",
        action="append",
        dest="selected_keys",
        help="Feature key selected for the action payload; repeat for each selected Feature.",
    )
    action_parser.add_argument(
        "--override",
        action="append",
        default=[],
        help="Selected size override in ISSUE-KEY=SIZE form; repeat as needed.",
    )
    action_parser.add_argument(
        "--clear-override",
        action="append",
        default=[],
        help="Remove a stored size override for ISSUE-KEY; repeat as needed.",
    )
    action_parser.add_argument(
        "--output",
        type=Path,
        help="Write payload JSON to this path instead of stdout.",
    )
    clear_parser = subparsers.add_parser(
        "clear-overrides",
        help="Restore original recommendations by removing stored apply-time overrides.",
    )
    clear_parser.add_argument("context", help="Sizing artifact context directory name")
    clear_parser.add_argument(
        "--key",
        action="append",
        dest="keys",
        default=[],
        help="Feature key to clear; repeat for multiple keys. Omit to clear every stored override.",
    )
    args = parser.parse_args(argv)

    try:
        directory = _directory(args.context)
        assessment_path = directory / "02-assessment.json"
        assessment = read_json(assessment_path)
        if not isinstance(assessment, dict) or not isinstance(assessment.get("features"), list):
            raise ValueError(f"{assessment_path} is not a finalized sizing assessment")

        if args.command == "preview":
            print(render_preview(assessment), end="")
            return 0

        known_keys = {item["key"] for item in assessment["features"] if isinstance(item, dict)}
        if args.command == "clear-overrides":
            requested = {key.strip() for key in args.keys} if args.keys else None
            decisions_obj, assessment, removed = _updated_overrides(
                directory, known_keys, {}, requested
            )
            _commit_override_update(directory, decisions_obj, assessment)
            print(
                f"Cleared {removed} apply-time override(s); assessment restored for "
                f"{len(assessment['features'])} Feature(s)."
            )
            return 0

        overrides = _parse_overrides(args.override, known_keys)
        cleared_keys = {value.strip() for value in args.clear_override}
        if args.all and args.selected_keys:
            raise ValueError("use --all or --approved-key, not both")
        if not args.all and not args.selected_keys:
            raise ValueError("select Features with --all or at least one --approved-key")
        selected = None if args.all else set(args.selected_keys)
        xxl_keys = {
            item["key"] for item in assessment["features"]
            if item["recommended_size"] == "XXL"
        }
        if selected is not None:
            unknown = selected - known_keys
            if unknown:
                raise ValueError(f"selected Features contain unknown key(s): {', '.join(sorted(unknown))}")
            if selected & xxl_keys:
                raise ValueError("XXL Features cannot be selected for Jira updates")
        if set(overrides) & xxl_keys:
            raise ValueError("XXL Features cannot be overridden during apply; split the Feature and rerun /assess")
        if selected is not None and set(overrides) - selected:
            raise ValueError("every size override must belong to a selected Feature")

        update_overrides = bool(overrides or cleared_keys)
        if update_overrides:
            decisions_obj, assessment, _ = _updated_overrides(
                directory, known_keys, overrides, cleared_keys
            )

        actions = _actions(assessment, selected)
        payload = {"context": args.context, "actions": actions}
        if update_overrides:
            _commit_override_update(directory, decisions_obj, assessment, args.output, payload)
        if args.output:
            if not update_overrides:
                write_json(args.output, payload)
            print(f"Prepared {len(actions)} Jira action(s) at {args.output}", file=sys.stderr)
        else:
            print(json.dumps(payload, ensure_ascii=False, separators=(",", ":")))
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
